name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        path: 'src'

    - name: Checkout builds
      uses: actions/checkout@master
      with:
        ref: 'builds'
        path: 'builds'

    - name: Checkout Aliucord
      uses: actions/checkout@master
      with:
        repository: 'Aliucord/Aliucord'
        path: 'repo'
        token: ${{ secrets.ACCESS_TOKEN }}

    - name: Setup JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Setup
      run: |
        echo "$ANDROID_HOME/build-tools/29.0.2" >> $GITHUB_PATH
        mkdir -p ~/bin
        wget https://github.com/Aliucord/buildtool/releases/download/v0.1.0/buildtool -P ~/bin
        chmod +x ~/bin/buildtool
        chmod +x $GITHUB_WORKSPACE/src/gradlew
        echo "{\"aliucord\":\"$GITHUB_WORKSPACE/Aliucord\",\"plugins\":\"$GITHUB_WORKSPACE/src\",\"androidSDK\":\"$ANDROID_HOME\",\"outputsPlugins\":\"$GITHUB_WORKSPACE/builds\"}" > ~/config.json

    - name: Build Plugins
      run: ~/bin/buildtool --config ~/config.json -p \*

    - name: Push builds
      run: |
        cd $GITHUB_WORKSPACE/builds
        cp ../src/updater.json .
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add *
        git commit -m "Build $GITHUB_SHA"
        git push 
